### ISSUE TITLE
[Feat] Notification Tab

### ISSUE THREAD

**Issue by ejalice** [mulmagi/iOS_SwiftUI#10]
**Issue : Feature**
Notification Tab 생성

**Description**
- Title 생성
- Alarm 버튼 생성
- SegmentedView 생성

**Todo**
- [x] Title 생성
- [x] Alarm 버튼 생성
- [x] SegmentedView 생성
    - [x] 내부 List 생성
    - [x] List 내부 View 구현
