### ISSUE TITLE
[Feat] QR스캔

### ISSUE THREAD

**Issue by ejalice** [mulmagi/iOS_SwiftUI#15]
**Issue : Feature**
- QR스캔 화면 생성

**Description**
- QR스캔 버튼 생성 (재사용 가능한 직사각형)
- QR스캔 화면 및 내부 화면 생성

**Todo**
- [x] 재사용 가능한 QR스캔 버튼 생성
 - [x] 카메라 연동
 - [x] QRScan 기능 생성
 - [x] 코드 입력 및 손전등 버튼 생성
