### ISSUE TITLE
[Feat] SignUp and Login

### ISSUE THREAD

**Issue by ejalice** [mulmagi/iOS_SwiftUI#20]
**Issue : Feature**
회원가입/로그인 기능

**Description**
회원가입/로그인을 위한 개인 정보 입력 및 전화번호 인증

**Todo**
- [x] 이름 입력 화면
- [x] 전화번호 입력 및 인증문자 화면
- [x] 이용약관 및 개인정보취급방침 화면

**Reference(Optional)**
로그인과 회원가입 플로우가 동일한지 한번더 백엔드 측과의 이야기를 통해 확인 필요.
