### ISSUE TITLE
[Feat] Rent Check

### ISSUE THREAD

**Issue by ejalice** [mulmagi/iOS_SwiftUI#22]
**Issue : Feature**
- 비밀번호로 대여하기 기능
- 대여/반납하기 확인 화면

**Description**
QR이 아닌 비밀번호로 대여하는 화면 및
대여 및 반납 최종 확인 화면 구현

**Todo**
- [x] OTP
- [x] OTP <-> Scan 화면 전환
- [x] 대여 확인 화면
- [x] 반납 확인 화면

**Reference(Optional)**
예외처리는 API 연결하면서 할 예정
