### ISSUE TITLE
[Feat] Menu Tab

### ISSUE THREAD

**Issue by ejalice** [mulmagi/iOS_SwiftUI#6]
**Issue : Feature**
Menu Tab 생성

**Description**
- UserBox 생성
- 포인트 버튼 생성
    - 충전하기 버튼 추가 생성
- 이용내역, 고객센터, 이용안내, 계정설정  버튼 함수 생성
    - 재사용 가능한 함수 구현
    - 함수 적용하여 MenuView에서 사용하기
- 공지사항 버튼 생성

**Todo**
- [x] UserBox 생성
- [x] 포인트 버튼 생성
- [x] 충전하기 버튼 추가 생성
- [x] 재사용 가능한 함수 구현 (이용내역, 고객센터, 이용안내, 계정설정)
    - [x] 함수 적용하여 MenuView에서 사용하기
- [x] 공지사항 버튼 생성
