### ISSUE TITLE
[Feat] UseInfoView

### ISSUE THREAD

**Issue by ejalice** [mulmagi/iOS_SwiftUI#8]
**Issue : Feature**
- 이용안내 화면 생성

**Description**
 - Menu Tab에서 이용안내를 눌렀을 때 보이는 화면 생성하기.

**Todo**
- [x] 재사용 가능한 배경 Box 생성
    - [x] 흰색 Text 들어가는 부분.
    - [x] TitleText 있는 경우 없는 경우 case 나눠서 생성.
- [x] Box를 사용해서 View 생성.
